services:
  mongodb: 
    image: mongo:latest
    container_name: crypto-tracker_mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db

  frontend: 
    build: ./frontend
    container_name: crypto-tracker_frontend
    restart: no
    volumes:
      - ./frontend/dist:/app/dist
    env_file:
      - ./frontend/.env-prod

  api:
   build: ./api
   container_name: crypto-tracker_api
   restart: always
   env_file:
    - ./api/.env-prod
   expose:
    - 8000:8000
   depends_on:
    - mongodb
   
  parser:
    build: ./parser
    container_name: crypto-tracker_parser
    restart: always
    env_file:
    - ./api/.env-prod
    depends_on:
      - mongodb