services:
  mongodb: 
    image: mongo:latest
    container_name: crypto-tracker_mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db